config section 'MESSENGERS'
	option connection_type 'vpn'
	option force_disable_fakeip '0'
	list server_community_lists 'geoblock'
	list server_community_lists 'ai'
	option disable_fakeip '1'
	option dscp_enabled '0'
	option enable_mixed_proxy '1'
	option per_section_tproxy '0'
	option no_sniff '0'
	option force_cidr_community '0'
	option community_lists_invert '0'
	option enable_user_lists '1'
	option enable_exclusions '0'
	option parental_control '0'
	option failover_enabled '0'
	option user_subnet_list_type 'text'
	list user_subnets_text '# TELEGRAM #'
	list user_subnets_text '############'
	list user_subnets_text '# IPv4-подсети Telegram'
	list user_subnets_text '91.105.192.0/23 91.108.4.0/22 91.108.8.0/21'
	list user_subnets_text '91.108.16.0/21 91.108.56.0/22 149.154.160.0/20'
	list user_subnets_text '185.76.151.0/24'
	list user_subnets_text '#IPv6-подсети Telegram'
	list user_subnets_text '2001:67c:4e8::/48 2001:b28:f23c::/48 2001:b28:f23d::/48'
	list user_subnets_text '2001:b28:f23f::/48 2a0a:f280::/32'
	option enabled '1'
	option interface 'awg10'
	option mixed_port '2080'
	list community_lists 'messengers'
	list community_lists 'meta'
	list user_lists '/etc/zeroblock/lists/zb-MESSENGERS.lst'

